/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppExplorerRouteImport } from './routes/_app.explorer'
import { Route as AppTrashRouteImport } from './routes/_app.trash'
import { Route as ApiGatewayRouteImport } from './routes/api.gateway'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiLocalRouteImport } from './routes/api.local'
import { Route as ApiSqliteRouteImport } from './routes/api.sqlite'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const ApiGatewayRoute = ApiGatewayRouteImport.update({
  id: '/api/gateway',
  path: '/api/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalRoute = ApiLocalRouteImport.update({
  id: '/api/local',
  path: '/api/local',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSqliteRoute = ApiSqliteRouteImport.update({
  id: '/api/sqlite',
  path: '/api/sqlite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AppAboutRoute
  '/account': typeof AppAccountRoute
  '/explorer': typeof AppExplorerRoute
  '/trash': typeof AppTrashRoute
  '/api/gateway': typeof ApiGatewayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/local': typeof ApiLocalRoute
  '/api/sqlite': typeof ApiSqliteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AppAboutRoute
  '/account': typeof AppAccountRoute
  '/explorer': typeof AppExplorerRoute
  '/trash': typeof AppTrashRoute
  '/api/gateway': typeof ApiGatewayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/local': typeof ApiLocalRoute
  '/api/sqlite': typeof ApiSqliteRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/explorer': typeof AppExplorerRoute
  '/_app/trash': typeof AppTrashRoute
  '/api/gateway': typeof ApiGatewayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/local': typeof ApiLocalRoute
  '/api/sqlite': typeof ApiSqliteRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/sitemap.xml'
    | '/about'
    | '/account'
    | '/explorer'
    | '/trash'
    | '/api/gateway'
    | '/api/health'
    | '/api/local'
    | '/api/sqlite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/sitemap.xml'
    | '/about'
    | '/account'
    | '/explorer'
    | '/trash'
    | '/api/gateway'
    | '/api/health'
    | '/api/local'
    | '/api/sqlite'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/sitemap.xml'
    | '/_app/about'
    | '/_app/account'
    | '/_app/explorer'
    | '/_app/trash'
    | '/api/gateway'
    | '/api/health'
    | '/api/local'
    | '/api/sqlite'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGatewayRoute: typeof ApiGatewayRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLocalRoute: typeof ApiLocalRoute
  ApiSqliteRoute: typeof ApiSqliteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorer': {
      id: '/_app/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/gateway': {
      id: '/api/gateway'
      path: '/api/gateway'
      fullPath: '/api/gateway'
      preLoaderRoute: typeof ApiGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local': {
      id: '/api/local'
      path: '/api/local'
      fullPath: '/api/local'
      preLoaderRoute: typeof ApiLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sqlite': {
      id: '/api/sqlite'
      path: '/api/sqlite'
      fullPath: '/api/sqlite'
      preLoaderRoute: typeof ApiSqliteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAccountRoute: typeof AppAccountRoute
  AppExplorerRoute: typeof AppExplorerRoute
  AppTrashRoute: typeof AppTrashRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAccountRoute: AppAccountRoute,
  AppExplorerRoute: AppExplorerRoute,
  AppTrashRoute: AppTrashRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGatewayRoute: ApiGatewayRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLocalRoute: ApiLocalRoute,
  ApiSqliteRoute: ApiSqliteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
