import {
  Add,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Book,
  Checkmark,
  CheckmarkOutline,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleSolid,
  CloudUpload,
  Code,
  Copy,
  Devices,
  Document,
  DocumentAdd,
  DocumentAudio,
  DocumentVideo,
  Download,
  DragVertical,
  Edit,
  Email,
  ErrorOutline,
  Folder,
  FolderAdd,
  FolderDetails,
  FolderMoveTo,
  FolderOpen,
  Grid,
  Help,
  Home,
  Image,
  Information,
  Laptop,
  Light,
  Link,
  List,
  Locked,
  LogoGithub,
  Maximize,
  Menu,
  Minimize,
  Moon,
  Move,
  Notification,
  OverflowMenuHorizontal,
  Password,
  Pause,
  Play,
  Renew,
  Reset,
  Save,
  Search,
  Security,
  ServerDns,
  Settings,
  Stop,
  Task,
  Terminal,
  Time,
  TrashCan,
  Upload,
  User,
  UserAvatar,
  UserMultiple,
  View,
  WarningAlt,
} from "@carbon/icons-react";

export {
  Add as Plus,
  Archive as FileArchive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Book as BookOpen,
  Checkmark as Check,
  CheckmarkOutline,
  CheckmarkOutline as CircleCheck,
  CheckmarkOutline as CheckCircle2,
  CheckmarkOutline as CheckCheck,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronLeft,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ChevronUp,
  CircleSolid as Circle,
  CircleSolid as XCircle,
  CloudUpload,
  CloudUpload as HardDriveUpload,
  Code as FileCode2,
  Copy,
  Devices,
  Devices as MonitorSmartphone,
  Document,
  Document as File,
  Document as FileIcon,
  Image as FileImage,
  Document as FileText,
  Document as FileSpreadsheet,
  Document as FileJson2,
  DocumentAdd as FilePlus2,
  DocumentAudio as FileAudio,
  DocumentVideo as FileVideo,
  Download,
  DragVertical as GripVertical,
  Edit as Pencil,
  Email as Mail,
  ErrorOutline as CircleX,
  ErrorOutline as CircleAlert,
  Folder,
  FolderAdd as FolderPlus,
  FolderDetails as FolderCheck,
  FolderDetails as FolderTree,
  FolderOpen,
  FolderMoveTo as FolderInput,
  Grid as Grid2X2,
  Help,
  Home,
  Image,
  Information as Info,
  Information,
  Information as Bug,
  Laptop,
  Light,
  Link as Link2,
  List,
  List as ListIcon,
  Locked as Lock,
  LogoGithub as Github,
  Maximize as Maximize2,
  Menu as PanelLeft,
  Menu as X,
  Minimize as Minimize2,
  Moon,
  Move as MoveRight,
  Notification as Bell,
  Notification,
  OverflowMenuHorizontal as MoreHorizontal,
  Password as KeyRound,
  Pause,
  Play,
  Renew,
  Renew as Loader2,
  Renew as RefreshCw,
  Renew as RotateCw,
  Reset as RotateCcw,
  Save,
  Search,
  Security,
  Security as Shield,
  Security as ShieldCheck,
  Security as ShieldAlert,
  ServerDns as Server,
  Settings,
  Stop,
  Task,
  Terminal,
  Terminal as TerminalSquare,
  Time as Clock,
  TrashCan,
  TrashCan as Trash2,
  Upload,
  Upload as UploadCloud,
  User,
  UserAvatar,
  UserAvatar as UserCircle2,
  UserMultiple as Users,
  View as Eye,
  View as Visibility,
  WarningAlt,
};
